name: "Install dependencies"
description: "Setup nodejs and install npm dependencies"
inputs:
  node-version:
    description: "Node version to use"
    required: false
    default: 18
runs:
  using: 'composite'
  steps:
    - name: Install nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install packages
      run: npm ci
      shell: bash