name: "Install dependencies"
description: "Setup nodejs and install npm dependencies"
inputs:
  node-version:
    description: "Node version to use"
    required: false
    default: 18
runs:
  using: 'composite'
  steps:
    - name: Install nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    - name: Cache dependencies
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: node-${{ hashFiles('**/package-lock.json') }}
    - name: Install packages
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
