name: CI Parallel
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
env: 
  workflow_node_version: 20
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.workflow_node_version }}
      - name: Install packages
        run: npm ci
      - name: Lint check
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.workflow_node_version }}
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      job_node_version: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.job_node_version }}
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build