name: CI Parallel
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
env: 
  NODE_VERSION: 20
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install packages
        run: npm ci
      - name: Lint check
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      MONGODB_USERNAME: ${{ secrets.MONGODB_DEV_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_DEV_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    env:
      JOB_NODE_VERSION: 20
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.JOB_NODE_VERSION }}
      - name: Deploy
        run: echo "Deploying application!!!"