name: CI Sequence
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      arch_type: ${{ steps.arch.outputs.arch_type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm ci
      - name: Arch type
        id: arch
        run: echo "arch_type='testing' >> $GITHUB_OUTPUT"
      - name: Lint check
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm ci
      - name: Print output from lint job
        run: echo "${{ needs.lint.outputs.arch_type }}"
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: |
            dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: dist-files
      - name: Output Files
        run: ls
      - name: Deploy
        run: echo "Deploying app!!!"