name: CI Sequence
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm ci
      - name: Lint check
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: |
            dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: echo "Deploying app!!!"