name: Lint Check
on: 
  push:
    branches:
      - 'main'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: npm ci
      - name: Lint check
        run: npm run lint

name: Run Tests
on: 
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npm run test

name: Build App
on: 
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build