name: Deploy application
on: push
jobs:
  deploy:
    build:
      runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
    steps:
      - run: npm ci
    steps:
      - run: npm test
    steps:
      - run: echo "Deploying application!!!"