name: Deploy application
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Deploy app
        run: echo "Deploying application!!!"